
/*
Task-1
Write a SQL query to retrieve all the customer information along with the total number of orders placed by each customer. Display the result in descending order of the number of orders.
*/

SELECT name, email, location, count(orders.customer_id) as "total" FROM customers JOIN orders on customers.customer_id = orders.customer_id GROUP BY orders.customer_id ORDER BY total DESC



/*
Task 2
Write a SQL query to retrieve the product name, quantity, and total amount for each order item. Display the result in ascending order of the order ID.
*/


SELECT name, quantity, total, orders.order_id FROM products JOIN order_items ON products.product_id = order_items.product_id JOIN orders on orders.order_id = order_items.order_id ORDER BY orders.order_id ASC;


/*
Task 3
Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.
*/

SELECT categories.name, SUM(unit_price * quantity) as total from categories JOIN products ON products.category_id = categories.category_id JOIN order_items ON order_items.product_id = products.product_id GROUP BY categories.category_id ORDER BY total DESC;


/*
Task 4

Write a SQL query to retrieve the top 5 customers who have made the highest total purchase amount. Display the customer name along with the total purchase amount in descending order of the purchase amount.
*/
SELECT customers.name, SUM(total) as total FROM customers JOIN orders ON orders.customer_id = customers.customer_id GROUP BY orders.customer_id ORDER BY total DESC LIMIT 5
